### ISSUE TITLE
Powerwall Companion won't load

### ISSUE THREAD

**Issue by GerryC60** [tomhollander/PowerwallCompanion#9]
Downloaded from Windows Store. Installed, but won't run. Freeezes on opening screen. No request to login to Powerwall.
Windows 10 Home 20H2
OS build: 19042.1348
..Gerry

**Comment by tomhollander** [comment]
Thanks for reporting Gerry. I'd seen a couple of reports of this in the app reviews, but I don't know the cause yet. 
One question (may or may not be relevant): do you have a current version of Microsoft Edge installed?

**Comment by GerryC60** [comment]
Yes I do.Microsoft EdgeVersion 96.0.1054.34 (Official build) (64-bit)..Gerry
    On Sunday, November 28, 2021, 01:04:16 PM PST, Tom Hollander ***@***.***> wrote:  
 
 


Thanks for reporting Gerry. I'd seen a couple of reports of this in the app reviews, but I don't know the cause yet.
One question (may or may not be relevant): do you have a current version of Microsoft Edge installed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GerryC60** [comment]
tom:BTW: I have installed your Android version (Powerwall Companion X, ver 1.21) on a Fire 7 tablet (7th Gen) running Fire OS 5.6.9.0. It seems to run OK and I appreciate that it runs on a version of Android based on ver 5. However getting to the Settings is a little difficult as the icon is at the extreme edge of the screen. I can enter the Settings, but it usually takes several tries. ..Gerry
    On Sunday, November 28, 2021, 01:04:16 PM PST, Tom Hollander ***@***.***> wrote:  
 
 


Thanks for reporting Gerry. I'd seen a couple of reports of this in the app reviews, but I don't know the cause yet.
One question (may or may not be relevant): do you have a current version of Microsoft Edge installed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tomhollander** [comment]
Thanks Gerry. The Android and Windows apps have different codebases so they won't always behave the same way.

I'm pretty sure the Windows app crash is due to a problem with the new Chromium based web view control which is needed to successfully sign in. It does work on most machines but I need to figure out why it fails on some. I'll keep looking at logs and try to figure out what's wrong.

It was deliberate to put the settings icon on Android near the corner of the screen, but on most devices it's still entirely in view. I'll see if I can figure out why it's partially off screen on your device.

**Comment by peppersass** [comment]
FWIW, it installs and runs fine in Windows 11 arm64 under Parallels on a MacBook M1 Max. That's about as out-there as you can get with Windows versions.

**Comment by tomhollander** [comment]
Hi @GerryC60 - I pushed out a new version with some changes which might help. Unfortunately since I don't know how to reproduce the problem I really don't know how likely it is that it's fixed, but please give it a go and let me know.

**Comment by GerryC60** [comment]
Tom:Tried the latest ver (3.3) but still doesn't load. Freezes on the splash screen with no login request. I can see the installed program under Settings/Apps. But I tried to locate the app using Control Panel, hoping to try to run it under different conditions. Control Panel doesn't find it. Maybe because it doesn't really load?I did try installing ver 3.2 on an older computer running an up to date Wondows 10 version. No improvement...Gerry
    On Saturday, December 4, 2021, 11:06:34 PM PST, Tom Hollander ***@***.***> wrote:  
 
 


Hi @GerryC60 - I pushed out a new version with some changes which might help. Unfortunately since I don't know how to reproduce the problem I really don't know how likely it is that it's fixed, but please give it a go and let me know.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GerryC60** [comment]
Tom:I tried it again, but with the Windows Task Mgr running. No tasks shown running in the Task Mgr...Gerry
    On Saturday, December 4, 2021, 11:06:34 PM PST, Tom Hollander ***@***.***> wrote:  
 
 


Hi @GerryC60 - I pushed out a new version with some changes which might help. Unfortunately since I don't know how to reproduce the problem I really don't know how likely it is that it's fixed, but please give it a go and let me know.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GerryC60** [comment]
Tom:I was intrigued by the Readme Notes for Powerwall Companion. We use a Windows phone running OS ver 8.1. However, the Microsoft store app doesn't seem to work properly.  And w/o that working, can't load any apps. It would be really nice to run the Powerwall app from the phone. Sigh....Gerry
    On Saturday, December 4, 2021, 11:06:34 PM PST, Tom Hollander ***@***.***> wrote:  
 
 


Hi @GerryC60 - I pushed out a new version with some changes which might help. Unfortunately since I don't know how to reproduce the problem I really don't know how likely it is that it's fixed, but please give it a go and let me know.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tomhollander** [comment]
Thanks for resting the new version @GerryC60. Sorry it didn't help - I'll keep trying.
Also apologies for the out of date release notes. The app was originally developed for Windows Phone and I kept it running as long as I could. Eventually Microsoft stopped releasing updates, and it became impossible for me to update the app to support changes to Tesla's authentication. If you want to run it on a phone now, you can use the Android version.

**Comment by tomhollander** [comment]
@GerryC60 Finally I think I have a solid lead. I believe it's necessary to install the "WebView2 Runtime" if it's not already on your machine. Can you please try downloading it from https://go.microsoft.com/fwlink/p/?LinkId=2124703 and let me know if the existing app loads?

Assuming it works, I'll look into how to bundle this with the app.

**Comment by GerryC60** [comment]
Tom:Works perfectly after loading the Webview2 Runtime. You should be able to include a hook to download the runtime. I saw a topic from Microsoft when I was searching for the runtime download. However I used your link which was direct and to the point. Thanks...Gerry
    On Tuesday, December 7, 2021, 08:59:06 PM PST, Tom Hollander ***@***.***> wrote:  
 
 


@GerryC60 Finally I think I have a solid lead. I believe it's necessary to install the "WebView2 Runtime" if it's not already on your machine. Can you please try downloading it from https://go.microsoft.com/fwlink/p/?LinkId=2124703 and let me know if the existing app loads?

Assuming it works, I'll look into how to bundle this with the app.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tomhollander** [comment]
Awesome! App has been updated to detect this situation, so future users shouldn't have this problem. Thanks for taking the time to report the issue and test my thoeries.

**Comment by GerryC60** [comment]
Tom:
You are welcome! I am happy to have a Windows app to check the Powerwall status. 
..Gerry

On December 7, 2021, at 10:13 PM, Tom Hollander ***@***.***> wrote:

Awesome! App has been updated to detect this situation, so future users shouldn't have this problem. Thanks for taking the time to report the issue and test my thoeries.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. ￼

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/tomhollander/PowerwallCompanion/issues/9#issuecomment-988530135">https://github.com/tomhollander/PowerwallCompanion/issues/9#issuecomment-988530135</a>", "url": "<a href="https://github.com/tomhollander/PowerwallCompanion/issues/9#issuecomment-988530135">https://github.com/tomhollander/PowerwallCompanion/issues/9#issuecomment-988530135</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
